### ISSUE TITLE
Alternate compress option to compress multiple files as single zip files

### ISSUE THREAD

**Issue by juliosecco** [akrabat/alfred-compress#1]
Well,
the object of the request is quite clear, I hope.
I would be glad to have a compress version that, having a multiple file selection, would produce an equivalent number of zip files each named with the correspondent file name.
I would be grateful if you could implement this thing too, thank you so much!

**Comment by akrabat** [comment]
This is a great idea. I've added it in version 0.7. Just press the Option (⌥) key when executing the action.

**Comment by juliosecco** [comment]
That's great Rob,
Works just fine, thank you so so much
if you come in Rome some day, I owe you a beer!
